### ISSUE TITLE
Breaks at SUMMARY.md Modification

### ISSUE THREAD

**Issue by dskvr** [matusnovak/doxybook#2]
Error
```
Modifying docs-build/SUMMARY.md
Traceback (most recent call last):
  File "/usr/local/bin/doxybook", line 11, in <module>
    load_entry_point('doxybook==2.1.0', 'console_scripts', 'doxybook')()
  File "/usr/local/lib/python3.7/site-packages/doxybook-2.1.0-py3.7.egg/doxybook/__init__.py", line 137, in main
  File "/usr/local/lib/python3.7/site-packages/doxybook-2.1.0-py3.7.egg/doxybook/generators/summary.py", line 60, in generate_summary
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
SUMMARY.md
```
[TEST](docs-build/index.md)
```

Been attempting to get Doxybook to function for a few hours, keep hitting this error.

**Comment by matusnovak** [comment]
Hi @dskvr 

Could you try with the following summary (see below)? I think you are missing `*<space>` before `[TEST...`. If that does not help, could you send me all the files so I can debug it? (Is your project on a public git repository?) 

```
# Summary

* [Introduction](README.md)
* [TEST](docs-build/index.md)
```

I have also added a warning that if the link can not be found in the SUMMARY.md. The master branch has been updated. Please use the new 2.1.1 version.

**Comment by dskvr** [comment]
Thanks for your prompt reply :+1: I'm going to continue troubleshooting with your provided information and get back to you.

**Comment by dskvr** [comment]
Hey @matusnovak,
I fixed this error by changing `offset = None` to `offset = 0` in `./doxybook/generators/summary.py` and recompiling. 

Once this was done, I received no errors and was able to generate a SUMMARY.md file.

**Comment by matusnovak** [comment]
That's interesting. Setting it to zero should not have worked. I will have a look into it right away.

**Comment by matusnovak** [comment]
Changes have been made based on your fix, the master branch has been updated. Closing the issue. Feel free to reopen if you still have the same problems with the summary.
