### ISSUE TITLE
No support for innergroups (modules) 

### ISSUE THREAD

**Issue by dskvr** [matusnovak/doxybook#3]
When `@ingroup` is used, doxygen assigns an `innergroup` element with a `refid` attribute to the 
`compound`. This is intended to be used to create hierarchies in groups, however, doxybook's SUMMARY.md modification step ignores this value (I presume also relevant to vuepress navigation config)

**Comment by matusnovak** [comment]
Hi @dskvr 

Sorry, innergroups are not supported at the moment. Give me few days and I will implement it.

**Comment by matusnovak** [comment]
Hi @dskvr 

I have implemented initial support for the requested innergroups. Would it be possible for you to test it? The feature is in the **[feature-innergroups](https://github.com/matusnovak/doxybook/tree/feature-innergroups) branch**.

The inner groups will be listed (as a tree) in the `SUMMARY.md` and also in the `modules.md` files. Additionally, the inner groups will be listed in the each individual parent (the group definition) file. 

The VuePress does not have the same `SUMMARY.md` as Gitbook (VuePress works slightly different), but the groups/modules will be listed exactly same in the `modules.md` and in the individual group files.

Let me know if it works for you.

**Comment by dskvr** [comment]
Sure thing, it might not be for a few days however, it's a busy week for me. I'll let you know.

**Comment by dskvr** [comment]
@matusnovak Works great :100: :+1:

**Comment by matusnovak** [comment]
@dskvr Awesome! Thanks for testing.

I have updated the master with the changes, and the version number has been increased to v2.1.3
