### ISSUE TITLE
Wrong formatting

### ISSUE THREAD

**Issue by ostapmk** [matusnovak/doxybook#6]
Consider [this](https://matusnovak.github.io/doxybook/gitbook/api/namespaceexample.html#enum-callbacktype). Whereas original Doxygen [shows](https://matusnovak.github.io/doxybook/original/namespaceexample.html#a002d84037f2ef097ebb0504482fa893d) it properly.
![image](https://user-images.githubusercontent.com/24300744/56075714-860b1f00-5dcf-11e9-8dd6-2e5d7f4f3923.png)

**Comment by matusnovak** [comment]
Hi @ostapmk 

Sorry for the late reply. Thank you for spotting the bug!

Fixed in 9c7df8d4fb08594d1eacd742754498c89fb23ccd as [v3.0.2](https://pypi.org/project/doxybook/3.0.2/)
