### ISSUE TITLE
Repeating parameters in macros

### ISSUE THREAD

**Issue by ricktobacco** [matusnovak/doxybook#8]
@matusnovak All is working very nicely, almost flawlessly, but I see the same parameters appearing twice for macros although the doxygen docs don't have this issue:
![Screenshot from 2019-11-08 22-17-25](https://user-images.githubusercontent.com/17416373/68522183-6f9a4880-0276-11ea-82e4-1d510a96d0ec.png)
![Screenshot from 2019-11-08 22-17-42](https://user-images.githubusercontent.com/17416373/68522184-6f9a4880-0276-11ea-803e-493674971147.png)

_Originally posted by @ricktobacco in https://github.com/matusnovak/doxybook/issues/7#issuecomment-552061336_

**Comment by matusnovak** [comment]
Fixed and released as https://pypi.org/project/doxybook/3.1.3/

I have used https://github.com/bancorprotocol/contracts_eos for debugging, and using the release v3.1.3 now correctly prints the markdown document for macros.

**Comment by ricktobacco** [comment]
Thank you so much for fixing this!!
